"""Solar PPA pricer with capture-price decomposition (Pieza 5).

Specification (CONTEXT.md / autonomous brief, 2026-05-30):

Reference asset: a 100 MW utility-scale PV plant in Andalucía
(lat 37.4, lon -5.0). The hourly generation profile is built from the
curated PVGIS panel (`data/curated/pvgis_panel.parquet`, SARAH3,
2019-2023) and perturbed with stochastic resource variability.

Contract structure (v1): a fixed fraction ``fixed_pct`` of generation is
sold at a fixed price ``strike``; the remaining ``spot_pct`` settles at
the hourly MIBEL spot. No caps or floors in v1.

The economic heart of a solar PPA is the **capture price** — the
generation-weighted average spot price the plant actually realises. Solar
output is concentrated in the midday hours when (in a renewable-heavy
system) the marginal price is depressed, so the capture price sits
*below* the simple baseload average. This cannibalisation is what makes
the fixed leg valuable to the generator and is modelled explicitly here
through a negative coupling between simulated price and the solar profile.

Pricing (in :func:`price_ppa`) is Monte Carlo on two coupled risk factors:

  1. **Generation paths** — the deterministic PVGIS hourly capacity-factor
     profile scaled by the nameplate capacity and multiplied by a
     per-path lognormal resource factor (interannual variability) and an
     optional per-hour multiplicative noise (forecast/cloud error).
  2. **Price paths** — the hourly MIBEL spot, generated by composing
     Pieza 1 (Schwartz-Smith forward level via
     :func:`models.forward.simulate`, optional) with Pieza 2 (the
     mean-reverting jump-diffusion of :func:`models.spot.simulate`), then
     overlaid with a solar-cannibalisation term. For the fast default
     path and the unit tests a self-contained reduced-form generator
     (:func:`simulate_price_paths`) is used so the heavy structural fits
     stay out of the test suite, exactly as the swing pricer keeps its
     stochastic model out of `tests/pricing/test_swing.py`.

The per-hour PPA cashflow follows the brief's formula::

    payoff_h = generation_h * (strike * fixed_pct + spot_h * spot_pct - cost_ppa)

summed over the hours of a contract year and present-valued over the
``duration_years`` with a flat real discount rate.

The pricer is deliberately **injectable**: :func:`price_ppa` will use
supplied ``price_paths`` / ``production_paths`` when given, and only fall
back to the internal generators otherwise. This keeps the valuation
arithmetic (capture price, structure split, discounting) testable against
deterministic paths.

References: the capture-price / cannibalisation framing follows the IEA
and IRENA solar-value literature; the price model is the Lucia-Schwartz /
Cartea-Figueroa MRJD of Pieza 2 (`models.spot`).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# Default Monte Carlo size for a fast, reproducible valuation. The brief's
# reported-valuation size (N_PATHS=50000) runs only under the
# ``requires_pod`` marker, off the CI fast lane.
DEFAULT_N_PATHS: int = 1000

# Hours in a (non-leap) contract year — the simulation horizon for one
# annual cashflow.
HOURS_PER_YEAR: int = 8760

# Flat real discount rate for the PV of the annual cashflows (EUR/MWh are
# already real). 7% is the mid-point of the WACC range quoted for Iberian
# utility-scale PV in the 2023-2024 advisory benchmarks.
DEFAULT_DISCOUNT_RATE: float = 0.07


# ---------------------------------------------------------------------------
# Contract definition
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PPA:
    """Terms of a solar power-purchase agreement.

    Attributes
    ----------
    capacity_mw
        Nameplate AC capacity in MW (the reference plant is 100 MW). An
        hour can never deliver more than this.
    plant_factor
        Expected annual capacity factor in ``(0, 1)`` — the mean of the
        hourly capacity-factor profile (~0.19 fixed-tilt, ~0.24 one-axis
        for the Andalucía site). Used as a sanity reference and to scale a
        flat profile when no PVGIS shape is supplied.
    fixed_pct
        Fraction of generation sold at the fixed ``strike``. In ``[0, 1]``.
    spot_pct
        Fraction of generation settled at the hourly spot. In ``[0, 1]``.
        ``fixed_pct + spot_pct`` must equal 1 (v1 has no merchant tail
        beyond the spot leg).
    strike
        Fixed-leg price in EUR/MWh paid to the generator for the fixed
        fraction of every MWh generated.
    duration_years
        Contract length in whole years (the reference deal is 10).
    cost_ppa
        Per-MWh offtake / O&M cost in EUR/MWh netted from every MWh
        generated. Default 0.0 (gross revenue).
    """

    capacity_mw: float
    plant_factor: float
    fixed_pct: float
    spot_pct: float
    strike: float
    duration_years: int
    cost_ppa: float = 0.0

    def __post_init__(self) -> None:
        if self.capacity_mw <= 0.0:
            raise ValueError("capacity_mw must be > 0")
        if not 0.0 < self.plant_factor < 1.0:
            raise ValueError("plant_factor must be in (0, 1)")
        for name, pct in (("fixed_pct", self.fixed_pct), ("spot_pct", self.spot_pct)):
            if not 0.0 <= pct <= 1.0:
                raise ValueError(f"{name} must be in [0, 1], got {pct}")
        if abs(self.fixed_pct + self.spot_pct - 1.0) > 1e-9:
            raise ValueError(
                "fixed_pct + spot_pct must equal 1 "
                f"(got {self.fixed_pct} + {self.spot_pct})"
            )
        if self.duration_years < 1:
            raise ValueError("duration_years must be >= 1")
        if not np.isfinite([self.strike, self.cost_ppa]).all():
            raise ValueError("strike and cost_ppa must be finite")


@dataclass(frozen=True)
class PriceModel:
    """Reduced-form hourly-price generator parameters.

    A deliberately small, self-contained model used for the fast default
    valuation and the unit tests. It reproduces the two features that
    drive a solar PPA's value without dragging the full Schwartz-Smith /
    MRJD machinery into the test suite:

    - a deterministic intraday (duck-curve) price shape, low overnight and
      midday, peaking in the evening ramp; and
    - a **cannibalisation** coupling that depresses the price in hours of
      high solar output, so the generation-weighted capture price falls
      below the baseload average.

    For an OMIP-consistent reported valuation use
    :func:`simulate_price_paths_from_spot` instead, which drives
    ``models.spot.simulate`` (Pieza 2) and, optionally, the forward level
    of ``models.forward`` (Pieza 1), then applies the same cannibalisation
    overlay.

    Attributes
    ----------
    baseload
        Mean baseload price level in EUR/MWh (e.g. ~60 for recent MIBEL).
    diurnal_amplitude
        Relative amplitude of the deterministic intraday shape in ``[0, 1)``.
        0 gives a flat shape; 0.3 a +/-30% midday-to-peak swing.
    cannibalisation
        Strength ``beta >= 0`` of the negative price response to the
        normalised solar excess. 0 removes the coupling (capture ~
        baseload up to the diurnal shape); larger values widen the
        capture discount.
    sigma
        Lognormal volatility of the multiplicative hourly price noise.
    ar1
        Hour-to-hour autocorrelation of the log-price noise in ``[0, 1)``.
    """

    baseload: float = 60.0
    diurnal_amplitude: float = 0.30
    cannibalisation: float = 0.45
    sigma: float = 0.25
    ar1: float = 0.80

    def __post_init__(self) -> None:
        if self.baseload <= 0.0:
            raise ValueError("baseload must be > 0")
        if not 0.0 <= self.diurnal_amplitude < 1.0:
            raise ValueError("diurnal_amplitude must be in [0, 1)")
        if self.cannibalisation < 0.0:
            raise ValueError("cannibalisation must be >= 0")
        if self.sigma < 0.0:
            raise ValueError("sigma must be >= 0")
        if not 0.0 <= self.ar1 < 1.0:
            raise ValueError("ar1 must be in [0, 1)")


@dataclass(frozen=True)
class PPAResult:
    """Valuation output of :func:`price_ppa`.

    Attributes
    ----------
    value
        Present value of the PPA to the generator over the full
        ``duration_years``, in EUR (mean across paths).
    std_error
        Monte Carlo standard error of ``value``.
    value_per_mwh
        Levelised value: ``value`` divided by the present value of total
        generation, in EUR/MWh. The all-in price the structure pays the
        generator net of ``cost_ppa``.
    capture_price_mean
        Mean across paths of the generation-weighted capture price
        (EUR/MWh).
    baseload_price_mean
        Mean across paths of the simple hourly-average (baseload) price
        (EUR/MWh).
    capture_ratio
        ``capture_price_mean / baseload_price_mean`` — the capture rate.
        Below 1 signals cannibalisation.
    annual_generation_mwh
        Mean annual generation (MWh) across paths.
    per_path_value
        Per-path present value over the contract, shape ``(n_paths,)``.
    n_paths, n_hours, duration_years
        Echoed problem dimensions.
    """

    value: float
    std_error: float
    value_per_mwh: float
    capture_price_mean: float
    baseload_price_mean: float
    capture_ratio: float
    annual_generation_mwh: float
    per_path_value: np.ndarray
    n_paths: int
    n_hours: int
    duration_years: int


# ---------------------------------------------------------------------------
# Path generators
# ---------------------------------------------------------------------------


def _normalise_profile(pv_profile: np.ndarray) -> np.ndarray:
    """Validate and coerce an hourly capacity-factor profile to ``float``."""
    cf = np.asarray(pv_profile, dtype=float)
    if cf.ndim != 1 or cf.size < 1:
        raise ValueError("pv_profile must be a non-empty 1D array")
    if not np.isfinite(cf).all():
        raise ValueError("pv_profile contains non-finite values")
    if (cf < 0.0).any() or (cf > 1.0).any():
        raise ValueError("pv_profile must be hourly capacity factors in [0, 1]")
    return cf


def simulate_production_paths(
    pv_profile: np.ndarray,
    capacity_mw: float,
    n_paths: int,
    *,
    resource_sigma: float = 0.05,
    hourly_sigma: float = 0.0,
    seed: int | None = None,
) -> np.ndarray:
    """Simulate hourly generation paths in MWh, shape ``(n_paths, n_hours)``.

    Each path multiplies the deterministic PVGIS hourly capacity-factor
    profile by the nameplate capacity, a per-path lognormal resource
    factor (interannual irradiance variability, ``resource_sigma``), and
    an optional per-hour lognormal multiplier (``hourly_sigma``, forecast /
    cloud noise). The result is clipped to ``[0, capacity_mw]`` — an hour
    cannot exceed nameplate.

    The lognormal multipliers are mean-one (``exp(s*z - s^2/2)``) so the
    expected generation equals ``capacity_mw * pv_profile`` and the plant
    factor is preserved in expectation.
    """
    cf = _normalise_profile(pv_profile)
    if capacity_mw <= 0.0:
        raise ValueError("capacity_mw must be > 0")
    if n_paths < 1:
        raise ValueError("n_paths must be >= 1")
    if resource_sigma < 0.0 or hourly_sigma < 0.0:
        raise ValueError("resource_sigma and hourly_sigma must be >= 0")

    rng = np.random.default_rng(seed)
    n_hours = cf.size
    base = capacity_mw * cf[np.newaxis, :]  # (1, n_hours) expected MWh

    if resource_sigma > 0.0:
        z = rng.standard_normal((n_paths, 1))
        resource = np.exp(resource_sigma * z - 0.5 * resource_sigma**2)
    else:
        resource = np.ones((n_paths, 1))

    gen = base * resource
    if hourly_sigma > 0.0:
        zz = rng.standard_normal((n_paths, n_hours))
        gen = gen * np.exp(hourly_sigma * zz - 0.5 * hourly_sigma**2)

    np.clip(gen, 0.0, capacity_mw, out=gen)
    return gen


def _diurnal_shape(n_hours: int, amplitude: float) -> np.ndarray:
    """Deterministic intraday price multiplier, mean ~1 over the day.

    A two-harmonic duck-curve: a midday trough and an evening (hour ~20
    local) peak. Returns a length-``n_hours`` array tiling the 24-hour
    pattern. ``amplitude`` scales the swing; 0 gives a flat unit shape."""
    hod = np.arange(n_hours) % 24
    # Evening-peaked, midday-troughed shape. Phase chosen so the minimum
    # sits around 13-14h (peak solar) and the maximum around 20-21h.
    angle = 2.0 * np.pi * (hod - 20) / 24.0
    shape = 1.0 + amplitude * np.cos(angle) - 0.35 * amplitude * np.cos(2.0 * angle)
    return shape


def simulate_price_paths(
    model: PriceModel,
    pv_profile: np.ndarray,
    n_paths: int,
    *,
    seed: int | None = None,
) -> np.ndarray:
    """Simulate hourly spot-price paths in EUR/MWh, shape ``(n_paths, n_hours)``.

    The reduced-form composition is::

        P_h = baseload * diurnal_h * (1 - beta * solar_excess_h) * noise_h

    where ``diurnal_h`` is the deterministic duck-curve shape,
    ``solar_excess_h`` is the demeaned, max-normalised capacity factor
    (positive in high-solar hours), ``beta`` is the cannibalisation
    strength, and ``noise_h`` is a mean-one lognormal AR(1) multiplier.

    The cannibalisation term is the only channel coupling price to
    generation; with ``beta > 0`` it pushes the price down precisely when
    output is high, which is what drives the capture price below baseload.
    Prices are floored at zero (MIBEL can clear at 0; v1 does not model
    negative prices).
    """
    cf = _normalise_profile(pv_profile)
    if n_paths < 1:
        raise ValueError("n_paths must be >= 1")

    rng = np.random.default_rng(seed)
    n_hours = cf.size

    diurnal = _diurnal_shape(n_hours, model.diurnal_amplitude)

    cf_max = float(cf.max())
    scale = cf_max if cf_max > 0.0 else 1.0
    solar_excess = (cf - cf.mean()) / scale  # demeaned, ~[-mean, 1-mean]/scale
    cannib = 1.0 - model.cannibalisation * solar_excess
    cannib = np.clip(cannib, 0.0, None)

    deterministic = model.baseload * diurnal * cannib  # (n_hours,)

    # AR(1) lognormal noise, mean-one per step.
    if model.sigma > 0.0:
        innov = rng.standard_normal((n_paths, n_hours))
        log_noise = np.empty((n_paths, n_hours))
        log_noise[:, 0] = model.sigma * innov[:, 0]
        for t in range(1, n_hours):
            log_noise[:, t] = model.ar1 * log_noise[:, t - 1] + model.sigma * innov[:, t]
        # Stationary variance of the AR(1) is sigma^2 / (1 - ar1^2);
        # subtract half of it to keep the multiplier mean-one.
        stat_var = model.sigma**2 / (1.0 - model.ar1**2)
        noise = np.exp(log_noise - 0.5 * stat_var)
    else:
        noise = np.ones((n_paths, n_hours))

    prices = deterministic[np.newaxis, :] * noise
    np.clip(prices, 0.0, None, out=prices)
    return prices


def simulate_price_paths_from_spot(
    spot_params,  # type: ignore[no-untyped-def]  # models.spot.SpotModelParams
    pv_profile: np.ndarray,
    n_paths: int,
    start,  # type: ignore[no-untyped-def]  # pd.Timestamp (UTC)
    *,
    cannibalisation: float = 0.45,
    initial_theta: float = 0.0,
    initial_residual: float = 0.0,
    seed: int | None = None,
) -> np.ndarray:
    """OMIP-consistent price paths: Pieza 2 (`models.spot.simulate`) plus the
    solar-cannibalisation overlay.

    This is the reported-valuation generator. ``models.spot.simulate``
    supplies the serially dependent hourly MIBEL spot (mean reversion,
    seasonality, Kou jumps); the solar overlay then multiplies each hour by
    ``1 - cannibalisation * solar_excess_h`` so the structural model — which
    is solar-blind — acquires the negative price/generation correlation that
    a renewable-heavy merit order produces. Anchor the slow factor to the
    OMIP forward curve (Pieza 1) by passing ``initial_theta`` from
    ``models.forward`` / ``models.spot.fit_with_forward_anchor``.

    Imported lazily so the heavy ``models.spot`` dependency (and its data)
    never loads on the fast default path or in the unit tests.
    """
    from mibel_derivatives.models import spot as spot_model

    cf = _normalise_profile(pv_profile)
    n_hours = cf.size
    prices = spot_model.simulate(
        spot_params,
        start,
        n_hours,
        n_paths,
        initial_theta=initial_theta,
        initial_residual=initial_residual,
        seed=seed,
    )

    cf_max = float(cf.max())
    scale = cf_max if cf_max > 0.0 else 1.0
    solar_excess = (cf - cf.mean()) / scale
    overlay = np.clip(1.0 - cannibalisation * solar_excess, 0.0, None)
    prices = prices * overlay[np.newaxis, :]
    np.clip(prices, 0.0, None, out=prices)
    return prices


# ---------------------------------------------------------------------------
# Pricer
# ---------------------------------------------------------------------------


def _annuity_factor(rate: float, duration_years: int) -> float:
    """Present value of one unit of annual cashflow received mid-year for
    ``duration_years`` years at a flat ``rate``.

    Mid-year discounting (exponent ``y - 0.5``) is the standard convention
    for cashflows that accrue continuously through the delivery year."""
    years = np.arange(1, duration_years + 1)
    return float(np.sum((1.0 + rate) ** -(years - 0.5)))


def price_ppa(
    ppa: PPA,
    *,
    pv_profile: np.ndarray | None = None,
    price_model: PriceModel | None = None,
    price_paths: np.ndarray | None = None,
    production_paths: np.ndarray | None = None,
    n_paths: int = DEFAULT_N_PATHS,
    discount_rate: float = DEFAULT_DISCOUNT_RATE,
    resource_sigma: float = 0.05,
    hourly_sigma: float = 0.0,
    seed: int | None = None,
) -> PPAResult:
    """Price a solar PPA by Monte Carlo with capture-price decomposition.

    Parameters
    ----------
    ppa
        :class:`PPA` contract terms.
    pv_profile
        Hourly capacity-factor profile in ``[0, 1]`` for one contract year
        (typically 8760 values from the curated PVGIS panel). Required
        unless both ``price_paths`` and ``production_paths`` are supplied.
    price_model
        :class:`PriceModel` for the internal reduced-form price generator.
        Defaults to ``PriceModel()`` when ``price_paths`` is not supplied.
    price_paths, production_paths
        Optional pre-simulated paths, each shape ``(n_paths, n_hours)``
        (EUR/MWh and MWh respectively). When supplied they are used
        verbatim — this is the path-agnostic mode used by the tests and by
        an OMIP-consistent reported valuation. The two must agree on shape.
    n_paths
        Monte Carlo paths when generating internally. Ignored for any
        factor whose paths are supplied.
    discount_rate
        Flat real annual discount rate for the multi-year PV.
    resource_sigma, hourly_sigma
        Generation-noise parameters forwarded to
        :func:`simulate_production_paths`.
    seed
        Reproducibility. A single seed drives both internal generators with
        independent sub-streams (price seed ``seed``, production seed
        ``seed + 1``) so the two factors are not spuriously correlated.

    Returns
    -------
    PPAResult
        Present value (EUR), levelised value (EUR/MWh), capture-price
        diagnostics and per-path values.

    Notes
    -----
    The per-hour cashflow is the brief's formula::

        payoff_h = generation_h * (strike*fixed_pct + spot_h*spot_pct - cost)

    summed to an annual cashflow per path and present-valued over the
    contract with the mid-year annuity factor. v1 treats each contract year
    as drawing the same annual scenario (the per-path annual cashflow times
    the annuity factor); interannual resampling is a documented extension.
    """
    # ---- resolve / generate the two factor path sets ----------------------
    if price_paths is not None or production_paths is not None:
        if price_paths is None or production_paths is None:
            raise ValueError(
                "supply both price_paths and production_paths, or neither"
            )
        price = np.asarray(price_paths, dtype=float)
        gen = np.asarray(production_paths, dtype=float)
        if price.ndim != 2 or gen.ndim != 2:
            raise ValueError("price_paths and production_paths must be 2D")
        if price.shape != gen.shape:
            raise ValueError(
                f"path shapes differ: price {price.shape} vs production {gen.shape}"
            )
        if not (np.isfinite(price).all() and np.isfinite(gen).all()):
            raise ValueError("supplied paths contain non-finite values")
    else:
        if pv_profile is None:
            raise ValueError(
                "pv_profile is required unless both path arrays are supplied"
            )
        cf = _normalise_profile(pv_profile)
        model = price_model if price_model is not None else PriceModel()
        price_seed = seed
        prod_seed = None if seed is None else seed + 1
        price = simulate_price_paths(model, cf, n_paths, seed=price_seed)
        gen = simulate_production_paths(
            cf,
            ppa.capacity_mw,
            n_paths,
            resource_sigma=resource_sigma,
            hourly_sigma=hourly_sigma,
            seed=prod_seed,
        )

    n_paths_eff, n_hours = price.shape

    # ---- capture-price decomposition --------------------------------------
    total_gen = gen.sum(axis=1)                       # (n_paths,) MWh / year
    revenue_spot = (gen * price).sum(axis=1)          # (n_paths,) EUR / year
    safe_gen = np.where(total_gen > 0.0, total_gen, np.nan)
    capture_price = revenue_spot / safe_gen           # generation-weighted
    baseload_price = price.mean(axis=1)               # simple hourly mean

    # ---- PPA structured cashflow (brief's per-hour formula) ---------------
    # generation_h * (strike*fixed_pct + spot_h*spot_pct - cost), summed.
    annual_cashflow = (
        ppa.fixed_pct * ppa.strike * total_gen
        + ppa.spot_pct * revenue_spot
        - ppa.cost_ppa * total_gen
    )

    annuity = _annuity_factor(discount_rate, ppa.duration_years)
    per_path_value = annuity * annual_cashflow

    value = float(per_path_value.mean())
    std_error = (
        float(per_path_value.std(ddof=1) / np.sqrt(n_paths_eff))
        if n_paths_eff > 1
        else 0.0
    )

    pv_total_gen = annuity * float(total_gen.mean())
    value_per_mwh = value / pv_total_gen if pv_total_gen > 0.0 else float("nan")

    capture_mean = float(np.nanmean(capture_price))
    baseload_mean = float(baseload_price.mean())
    capture_ratio = capture_mean / baseload_mean if baseload_mean > 0.0 else float("nan")

    return PPAResult(
        value=value,
        std_error=std_error,
        value_per_mwh=value_per_mwh,
        capture_price_mean=capture_mean,
        baseload_price_mean=baseload_mean,
        capture_ratio=capture_ratio,
        annual_generation_mwh=float(total_gen.mean()),
        per_path_value=per_path_value,
        n_paths=n_paths_eff,
        n_hours=n_hours,
        duration_years=ppa.duration_years,
    )


# ---------------------------------------------------------------------------
# Curated-data helper
# ---------------------------------------------------------------------------


def representative_year_profile(
    config: str = "fixed_35deg_south",
    *,
    panel=None,  # type: ignore[no-untyped-def]  # pd.DataFrame | None
) -> np.ndarray:
    """Build an 8760-hour capacity-factor profile from the PVGIS panel.

    Averages the per-hour capacity factor (``p_w / 1000`` for the 1 kWp
    reference) across the available years for ``config``, indexed by
    (month, day-of-year-hour) so the diurnal and seasonal shape survive.
    The result is a deterministic "typical year" hourly profile in
    ``[0, 1]`` suitable for :func:`price_ppa`.

    Loads the curated parquet lazily when ``panel`` is not supplied so the
    module imports cleanly without the data present.
    """
    if panel is None:
        import pandas as pd

        from mibel_derivatives.data import _paths

        panel = pd.read_parquet(_paths.curated_path("pvgis_panel.parquet"))

    sub = panel[panel["config"] == config].copy()
    if sub.empty:
        raise ValueError(f"no rows for config={config!r} in the PVGIS panel")

    dt = sub["dt_utc"]
    # Group by (month, day, hour) and average across years; drop Feb-29 so
    # every typical year is 8760 hours.
    key_month = dt.dt.month
    key_day = dt.dt.day
    key_hour = dt.dt.hour
    sub = sub.assign(_m=key_month, _d=key_day, _h=key_hour)
    sub = sub[~((sub["_m"] == 2) & (sub["_d"] == 29))]
    cf = (sub["p_w"] / 1000.0).clip(lower=0.0, upper=1.0)
    sub = sub.assign(_cf=cf)
    typical = (
        sub.groupby(["_m", "_d", "_h"], sort=True)["_cf"]
        .mean()
        .sort_index()
        .to_numpy()
    )
    return typical.astype(float)


__all__ = [
    "DEFAULT_DISCOUNT_RATE",
    "DEFAULT_N_PATHS",
    "HOURS_PER_YEAR",
    "PPA",
    "PPAResult",
    "PriceModel",
    "price_ppa",
    "representative_year_profile",
    "simulate_price_paths",
    "simulate_price_paths_from_spot",
    "simulate_production_paths",
]
